{"level":"info","msg":"Using namespace 'default'","time":"2024-06-13T10:14:48+02:00"}
{"level":"info","msg":"Using kube context 'loft-vcluster_nielscluster_default'","time":"2024-06-13T10:14:48+02:00"}
deploy:python-demo Deploying chart C:\Users\kro\.devspace\component-chart\component-chart-0.9.1.tgz (python-demo) with helm...deploy:python-demo Downloading helm...deploy:python-demo Deployed helm chart (Release revision: 1)deploy:python-demo Successfully deployed python-demo with helmdev:python-demo Created PVC python-demo-pvc for replaced pod python-demo-devspacedev:python-demo Waiting for pod to become ready...dev:python-demo Pod python-demo-devspace-6c58d46678-kd2fm: 0/2 nodes are available: persistentvolumeclaim "python-demo-pvc-x-default-x-nielscluster" not found. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling. (FailedScheduling)dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-kd2fm has status: Init:0/2dev:python-demo Selected pod python-demo-devspace-6c58d46678-kd2fmdev:python-demo sync  Sync started on: . <-> /workspaces/python-demodev:python-demo sync  Waiting for initial sync to completedev:python-demo sync  Initial sync completeddev:python-demo ssh   Port forwarding started on: 11805 -> 8022dev:python-demo ssh   Use 'ssh python-demo.devspace' to connect via SSH{"level":"info","msg":"Using namespace 'default'","time":"2024-06-13T11:12:27+02:00"}
{"level":"info","msg":"Using kube context 'loft-vcluster_nielscluster_default'","time":"2024-06-13T11:12:27+02:00"}
deploy:python-demo Skipping deployment python-demodev:python-demo Waiting for pod to become ready...dev:python-demo Pod python-demo-devspace-6c58d46678-t57s6: Multi-Attach error for volume "pvc-ed3dbe42-9607-4dad-a9a7-097b3da25756" Volume is already used by pod(s) python-demo-devspace-6c58d46678-kd2fm-x-default-x-nielscluster (FailedAttachVolume)dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-t57s6 has status: Init:0/2dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-t57s6 has status: Init:0/2dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-t57s6 has status: Init:0/2dev:python-demo Selected pod python-demo-devspace-6c58d46678-t57s6dev:python-demo sync  Sync started on: . <-> /workspaces/python-demodev:python-demo sync  Waiting for initial sync to completedev:python-demo sync  Initial sync completeddev:python-demo ssh   Port forwarding started on: 11805 -> 8022dev:python-demo ssh   Use 'ssh python-demo.devspace' to connect via SSH{"level":"info","msg":"Using namespace 'default'","time":"2024-06-13T11:16:50+02:00"}
{"level":"info","msg":"Using kube context 'loft-vcluster_nielscluster_default'","time":"2024-06-13T11:16:50+02:00"}
deploy:python-demo Skipping deployment python-demodev:python-demo Waiting for pod to become ready...dev:python-demo Pod python-demo-devspace-6c58d46678-jlt7t: Multi-Attach error for volume "pvc-ed3dbe42-9607-4dad-a9a7-097b3da25756" Volume is already used by pod(s) python-demo-devspace-6c58d46678-t57s6-x-default-x-nielscluster (FailedAttachVolume)dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-jlt7t has status: Init:0/2dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-jlt7t has status: Init:0/2dev:python-demo DevSpace is waiting, because Pod python-demo-devspace-6c58d46678-jlt7t has status: Init:0/2dev:python-demo Selected pod python-demo-devspace-6c58d46678-jlt7tdev:python-demo sync  Sync started on: . <-> /workspaces/python-demodev:python-demo sync  Waiting for initial sync to completedev:python-demo sync  Initial sync completeddev:python-demo ssh   Port forwarding started on: 11805 -> 8022dev:python-demo ssh   Use 'ssh python-demo.devspace' to connect via SSHdev:python-demo ssh   Restarting because: lost connection to poddev:python-demo ssh   Error restarting port-forwarding: forward ports: error upgrading connection: unable to upgrade connection: error dialing backend: dial tcp 10.0.0.1:443: connect: connection refuseddev:python-demo ssh   Will try again in 15 secondsdev:python-demo ssh   Port forwarding started on: 11805 -> 8022dev:python-demo sync  Restarting because: ping connection: rpc error: code = DeadlineExceeded desc = context deadline exceeded